name: isibi
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  appinio_video_player: ^1.2.2
  auto_size_text: 3.0.0
  camera: ^0.10.5+4
  chewie: ^1.7.1
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.3
  easy_search_bar: ^2.5.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  flutter_tflite: ^1.0.1
  get: 4.6.5
  get_storage: ^2.1.1
  google_fonts: ^5.1.0
  google_ml_kit: ^0.16.2
  http: ^1.1.0
  image: ^3.2.0
  introduction_screen: ^3.1.12
  lint: ^2.1.2
  permission_handler: ^11.0.0
  smooth_page_indicator: ^1.1.0
  video_player: ^2.7.2
  webview_flutter: ^4.4.1

dev_dependencies:
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/isibi.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/ic_foreground.png"

flutter:
  assets:
    - assets/models/
    - assets/images/
    - assets/icons/
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Italic.ttf
  uses-material-design: true
